### ISSUE TITLE
Application not working after reboot

### ISSUE THREAD

**Issue by nkobber** [UnlimitedStack/HideVolumeOSD#1]
The application works as intended after installing.
But after a reboot the Volume OSD is back even though HideVolumeOSD is running. Toggling it hidden also does not work.

I'm using Windows 10 with newest updates

**Comment by Keavon** [comment]
Same issue here.

**Comment by squatOn** [comment]
I am experiencing this, too. Upon reboot, I just quit the app (since it starts automatically), and re-open Hide OSD and it re-hides. Not a huge problem, but does put some manual work into using this.

**Comment by kantarellen** [comment]
Fixed in 1.2.

**Comment by pbakes** [comment]
Seems to only work intermittently in Windows 10 2004, silent version or tray version.

**Comment by UnlimitedStack** [comment]
@TheCakeIsNaOH solved the problem 👍
