### ISSUE TITLE
Popup on system startup

### ISSUE THREAD

**Issue by jairocontreras** [UnlimitedStack/HideVolumeOSD#10]
Adding the app to startup makes the volume bar popup just once without having pressed any media controls.

**Comment by pbakes** [comment]
If I try to add it as a startup item it says "Server Error: OSD window not found" It also happens if I also create a delayed startup task in Task Scheduler.

**Comment by jairocontreras** [comment]
not solved :( and add to that the volume is set to 98%

**Comment by pbakes** [comment]
@jairocontreras I noticed after one of the Windows updates it also happened once to me. This is what I did. During a normal user session, open HideVolumeOSD, toggle the program by clicking twice on the tray icon, and restart the computer.
1.3 currently working as it should during startup.
