### ISSUE TITLE
Add README.md file and download links.

### ISSUE THREAD

**Issue by shivanshu-semwal** [UnlimitedStack/HideVolumeOSD#11]
Thanks for this awesome project. But can you add a `README.md` describing this project and giving the download link. I found this project [http://wordpress.venturi.de/?p=1](http://wordpress.venturi.de/?p=1)  here.

**Comment by Niotferdi** [comment]
I want to add: version 1.2 worked for me, but another version did not work. Keep this in mind when downloading.
