### ISSUE TITLE
Screen brightness not showing

### ISSUE THREAD

**Issue by cozyplanes** [UnlimitedStack/HideVolumeOSD#3]
I have a laptop that displays the brightness control in the same spot where `volumeOSD` appears. Now when I enable `HideVolumeOSD`, it makes the `brightness control OSD` disappear as well.

**Comment by lord-ne** [comment]
Probably because the way the program identifies the volume OSD also catches the brightness one. I doubt it can be fixed. If you want, I can design a custom OSD for your brightness using Autohotkey (I'm really bored). Just tell me what buttons your laptop uses to change brightness.

**Comment by cozyplanes** [comment]
I don't actually care now, i am used to it, but 
```
Up arrow button is brightness up
Down arrow button is brightness down
Left arrow button is volume down
Right arrow button is volume up 
```

**Comment by lord-ne** [comment]
Here.

[VolumeOSD.zip](https://github.com/UnlimitedStack/HideVolumeOSD/files/1829389/VolumeOSD.zip)
