### ISSUE TITLE
Severe error

### ISSUE THREAD

**Issue by PINCHO93** [UnlimitedStack/HideVolumeOSD#5]
After a reboot, I get the following error.
![image](https://user-images.githubusercontent.com/13229233/67908290-4c3b1380-fb7b-11e9-9a2d-cd766bbb298c.png)

**Comment by JorisDebonnet** [comment]
@PINCHO93, I also had this issue since a few weeks ago. So I uninstalled HideVolumeOSD, looked up the website again, and installed HideVolumeOSD 1.2.

Now it just works again ... 😊 Maybe that works for you too.

**Comment by Badsheep** [comment]
Hello,

Same here with version 1.2.
