### ISSUE TITLE
Sometimes "Missing OSD windows" error after restart

### ISSUE THREAD

**Issue by Girofox** [UnlimitedStack/HideVolumeOSD#7]
Sometimes the programm cannot find osd windows, when you restart Windows and then not adjusting volume manually before the program starts. I tried to delay startup with task scheduler and admin rights but no luck.

**Comment by Badsheep** [comment]
Hello, same issue here.

**Comment by Girofox** [comment]
I found a fix, disable auto run at boot (in Task Manager) and then create a new task with Task scheduler which runs HideVolumeOSD.exe -hide at logon with elevated privileges. Maybe you need to delay task execution by 30 seconds.

**Comment by Girofox** [comment]
Here is my XML of the task, you can import it right into Task Scheduler

`<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2020-05-13T13:54:45.2188392</Date>
    <Author>DESKTOP-JK83GB4\mwaci</Author>
    <URI>\Custom\HideVolumeOSD</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <GroupId>S-1-5-32-545</GroupId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\Program</Command>
      <Arguments>Files (x86)\HideVolumeOSD\HideVolumeOSD.exe -hide</Arguments>
      <WorkingDirectory>C:\Program Files (x86)\HideVolumeOSD</WorkingDirectory>
    </Exec>
  </Actions>
</Task>`

[HideVolumeOSD.zip](https://github.com/UnlimitedStack/HideVolumeOSD/files/4837018/HideVolumeOSD.zip)

**Comment by madebyfabian** [comment]
Same issue here, even when I switch between Windows Users.
